# This workflow will build a MuleSoft project and deploy to CloudHub

name: Maven build Fetching "settings.xml"

on:
  pull_request:
    types:
    - closed
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
    branches:
    - Development
    
    
jobs:
  build:
jobs:
  diff_and_print:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Git diff
      run: |
        git checkout feature
        git diff feature..feature -- path/to/file > file_changes.txt

    - name: Save changes to file
      uses: actions/upload-artifact@v2
      with:
        name: file_changes
        path: file_changes.txt
